### ISSUE TITLE
enable wc_lang.core.Model to be constructed from outside model repo directories (or their children)

### ISSUE THREAD

**Issue by aesundstrom** [KarrLab/wc_lang#8]
Presently, the wc_lang/core.py code assumes it is being executed from within the repo — i.e., that CWD is at or below <repo root dir>. But one ought to be able to execute the code from anywhere.

In other words...

`<repo root dor>/.../<code dir>/ $ python 3.6 <code file name>`

produces no error, whereas...

`/tmp/ $ python 3.6 /path/to/<code file name>`

produces (in the case of my executing h1_hesc code that imports wc_lang):

```
Traceback (most recent call last):
  File "/Users/aes/dev/gitroot/Karr_Lab/h1_hesc/cell_cycle/tyson_2011/hybrid_model/hybrid_model_rules.py", line 23, in <module>
    H1_hESC_model = Model(id='programmatic_model', name='Programmatic model')
  File "/usr/local/lib/python3.6/site-packages/wc_lang/core.py", line 688, in __init__
    self.revision = git.get_repo_metadata().revision
  File "/usr/local/lib/python3.6/site-packages/wc_utils/util/git.py", line 24, in get_repo_metadata
    repo = git.Repo(dirname, search_parent_directories=search_parent_directories)
  File "/usr/local/lib/python3.6/site-packages/git/repo/base.py", line 161, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /tmp/
```

**Comment by jonrkarr** [comment]
Implemented in 4aa666166a88699a7c9616513fd0b6d3a893d952

Metadata collection moved from `wc_lang.core.Model` to `wc_lang.util`, `wc_lang.io`, and `wc_lang.__main__` to enable `wc_lang` to be used without Git and to enable `wc_lang` to be used from any directory
